"Category: CI":
  - .github/workflows/**/*


"Category: Cogs - Admin":
  # Source
  - redbot/cogs/admin/*
"Category: Cogs - Alias":
  # Source
  - redbot/cogs/alias/*
  # Tests
  - redbot/pytest/alias.py
  - tests/cogs/test_alias.py
"Category: Cogs - Audio":
  # Source
  - any:
      - redbot/cogs/audio/**/*
      - "!redbot/cogs/audio/**/locales/*"
  # Tests
  - tests/cogs/audio/**/*
"Category: Cogs - Bank": []  # historical label for a removed cog
"Category: Cogs - Cleanup":
  # Source
  - redbot/cogs/cleanup/*
"Category: Cogs - CustomCommands":
  # Source
  - redbot/cogs/customcom/*
"Category: Cogs - Dev":
  # Source
  - redbot/core/dev_commands.py
  # Tests
  - tests/core/test_dev_commands.py
"Category: Cogs - Downloader":
  # Source
  - redbot/cogs/downloader/*
  # Tests
  - redbot/pytest/downloader.py
  - redbot/pytest/downloader_testrepo.*
  - tests/cogs/downloader/**/*
"Category: Cogs - Economy":
  # Source
  - redbot/cogs/economy/*
  # Tests
  - redbot/pytest/economy.py
  - tests/cogs/test_economy.py
"Category: Cogs - Filter":
  # Source
  - redbot/cogs/filter/*
"Category: Cogs - General":
  # Source
  - redbot/cogs/general/*
"Category: Cogs - Image":
  # Source
  - redbot/cogs/image/*
"Category: Cogs - Mod":
  # Source
  - redbot/cogs/mod/*
  # Tests
  - redbot/pytest/mod.py
  - tests/cogs/test_mod.py
"Category: Cogs - Modlog":
  # Source
  - redbot/cogs/modlog/*
"Category: Cogs - Mutes":
  # Source
  - redbot/cogs/mutes/*
"Category: Cogs - Permissions":
  # Source
  - redbot/cogs/permissions/*
  # Tests
  - redbot/pytest/permissions.py
  - tests/cogs/test_permissions.py
"Category: Cogs - Reports":
  # Source
  - redbot/cogs/reports/*
"Category: Cogs - Streams":
  # Source
  - redbot/cogs/streams/*
"Category: Cogs - Trivia":
  # Source
  - redbot/cogs/trivia/*
  # Tests
  - tests/cogs/test_trivia.py
"Category: Cogs - Trivia - Lists":
  - redbot/cogs/trivia/data/lists/*
"Category: Cogs - Warnings":
  # Source
  - redbot/cogs/warnings/*


"Category: Core - API - Audio": []  # potential future feature
"Category: Core - API - Bank":
  # Source
  - redbot/core/bank.py
"Category: Core - API - App Commands Package":
  # Source
  - redbot/core/app_commands/*
  # Tests
  - tests/core/test_app_commands.py
"Category: Core - API - Commands Package":
  # Source
  - any:
      - redbot/core/commands/*
      - "!redbot/core/commands/help.py"
  # this isn't in commands package but it just re-exports things from it
  - redbot/core/checks.py
  # Tests
  - tests/core/test_commands.py
"Category: Core - API - Config":
  # Source
  - any:
      - redbot/core/_drivers/**/*
      - "!redbot/core/_drivers/**/locales/*"
  - redbot/core/config.py
  # Tests
  - tests/core/test_config.py
"Category: Core - API - Other":
  # Source
  - redbot/__init__.py
  - redbot/core/__init__.py
  - redbot/core/data_manager.py
  - redbot/core/errors.py
  - redbot/core/tree.py
  # Tests
  - redbot/pytest/data_manager.py
  - tests/core/test_cog_manager.py
  - tests/core/test_data_manager.py
  - tests/core/test_version.py
"Category: Core - API - Utils Package":
  # Source
  - any:
    - redbot/core/utils/*
    - "!redbot/core/utils/_internal_utils.py"
  # Tests
  - tests/core/test_utils.py
"Category: Core - Bot Class":
  # Source
  - redbot/core/bot.py
"Category: Core - Bot Commands":
  # Source
  - redbot/core/core_commands.py
  - redbot/core/_diagnoser.py
"Category: Core - Command-line Interfaces":
  - redbot/__main__.py
  - redbot/logging.py
  - redbot/core/_cli.py
  - redbot/core/_debuginfo.py
  - redbot/setup.py
"Category: Core - Help":
  - redbot/core/commands/help.py
"Category: Core - i18n":
  # Source
  - redbot/core/i18n.py
  # Locale files
  - redbot/**/locales/*
"Category: Core - Modlog":
  # Source
  - redbot/core/generic_casetypes.py
  - redbot/core/modlog.py
"Category: Core - Other Internals":
  # Source
  - redbot/core/_cog_manager.py
  - redbot/core/_events.py
  - redbot/core/_global_checks.py
  - redbot/core/_settings_caches.py
  - redbot/core/_sharedlibdeprecation.py
  - redbot/core/utils/_internal_utils.py
  # Tests
  - redbot/pytest/__init__.py
  - redbot/pytest/cog_manager.py
  - redbot/pytest/core.py
  - tests/core/test_installation.py
"Category: Core - RPC/ZMQ":
  # Source
  - redbot/core/_rpc.py
  # Tests
  - redbot/pytest/rpc.py
  - tests/core/test_rpc.py
  - tests/rpc_test.html


"Category: Docker": []  # potential future feature


"Category: Meta":
  # top-level files
  - any:
      - '*'
      - '!README.md'
      - '!CHANGES.rst'
  # .gitattributes files
  - '**/.gitattributes'
  # GitHub configuration files, with the exception of CI configuration
  - .github/*
  - .github/ISSUE_TEMPLATE/*
  - .github/PULL_REQUEST_TEMPLATE/*
  # empty file
  - redbot/cogs/__init__.py
  # py.typed file
  - redbot/py.typed
  # requirements files
  - requirements/*
  # schema files
  - schema/*
  # tests configuration, global fixtures, etc.
  - tests/conftest.py
  - tests/__init__.py
  - tests/*/__init__.py
  # repository tools
  - tools/*


# "Category: RPC/ZMQ methods": []  # can't be matched by file patterns


"Category: Vendored Packages":
  - redbot/vendored/**/*
